version: 1
update_configs:
  - package_manager: 'javascript'
    directory: '/'
    update_schedule: 'daily'
    version_requirement_updates: 'auto'
    automerged_updates:
      - match:
          dependency_type: 'all'
          update_type: 'in_range'
